/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab11;

/**
 *
 * @author ADMIN
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Bai3 extends javax.swing.JFrame {
    private JCheckBox chkChoiDan, chkNgheNhac, chkXemPhim, chkDuLich;
    private JButton btnXacNhan;
    private JTextArea txtKetQua;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bai3.class.getName());

    /**
     * Creates new form Bai3
     */
    public Bai3() {
        initComponents();
         setTitle("Chọn sở thích");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        chkChoiDan = new JCheckBox("Chơi Đàn");
        chkNgheNhac = new JCheckBox("Nghe nhạc");
        chkXemPhim = new JCheckBox("Xem phim");
        chkDuLich = new JCheckBox("Du lịch");
        btnXacNhan = new JButton("Xác nhận");
        txtKetQua = new JTextArea(5, 20);
        txtKetQua.setEditable(false);
        JPanel pnlCheckbox = new JPanel(new GridLayout(4, 1));
        pnlCheckbox.add(chkChoiDan);
        pnlCheckbox.add(chkNgheNhac);
        pnlCheckbox.add(chkXemPhim);
        pnlCheckbox.add(chkDuLich);

        setLayout(new BorderLayout());
        add(pnlCheckbox, BorderLayout.WEST);
        add(new JScrollPane(txtKetQua), BorderLayout.CENTER);
        add(btnXacNhan, BorderLayout.SOUTH);

      
        btnXacNhan.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                txtKetQua.setText("Sở thích đã chọn:\n");

                if (chkChoiDan.isSelected())
                    txtKetQua.append("- Chơi Đàn\n");
                if (chkNgheNhac.isSelected())
                    txtKetQua.append("- Nghe nhạc\n");
                if (chkXemPhim.isSelected())
                    txtKetQua.append("- Xem phim\n");
                if (chkDuLich.isSelected())
                    txtKetQua.append("- Du lịch\n");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        new Bai3().setVisible(true);
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Bai3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
