/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab11;

/**
 *
 * @author ADMIN
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
public class Bai4 extends javax.swing.JFrame {
     private JRadioButton rdoNam, rdoNu, rdoKhac;
    private ButtonGroup groupGioiTinh;
    private JButton btnXacNhan;
    private JLabel lblKetQua;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bai4.class.getName());

    /**
     * Creates new form Bai4
     */
    public Bai4() {
        initComponents();
         setTitle("Chọn giới tính");
        setSize(350, 200);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        rdoNam = new JRadioButton("Nam");
        rdoNu = new JRadioButton("Nữ");
        rdoKhac = new JRadioButton("Khác");

        groupGioiTinh = new ButtonGroup();
        groupGioiTinh.add(rdoNam);
        groupGioiTinh.add(rdoNu);
        groupGioiTinh.add(rdoKhac);

        // Button
        btnXacNhan = new JButton("Xác nhận");

        // Label hiển thị kết quả
        lblKetQua = new JLabel("Giới tính đã chọn: ");

        // Panel RadioButton
        JPanel pnlRadio = new JPanel(new GridLayout(3, 1));
        pnlRadio.add(rdoNam);
        pnlRadio.add(rdoNu);
        pnlRadio.add(rdoKhac);

        // Layout
        setLayout(new BorderLayout());
        add(pnlRadio, BorderLayout.CENTER);
        add(btnXacNhan, BorderLayout.SOUTH);
        add(lblKetQua, BorderLayout.NORTH);

        btnXacNhan.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String gioiTinh = "";

                if (rdoNam.isSelected())
                    gioiTinh = "Nam";
                else if (rdoNu.isSelected())
                    gioiTinh = "Nữ";
                else if (rdoKhac.isSelected())
                    gioiTinh = "Khác";

                if (gioiTinh.isEmpty()) {
                    lblKetQua.setText("Vui lòng chọn giới tính!");
                } else {
                    lblKetQua.setText("Giới tính đã chọn: " + gioiTinh);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Bai4().setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Bai4().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
