/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab11;

/**
 *
 * @author ADMIN
 */
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
public class Bai6 extends javax.swing.JFrame {
    private JTextField txtEmail;
    private JLabel lblThongBao;
     private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bai6.class.getName());
    /**
     * Creates new form Bai6
     */
    public Bai6() {
        initComponents();
        setTitle("Kiểm tra email realtime");
        setSize(400, 150);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        JLabel lblEmail = new JLabel("Email:");
        txtEmail = new JTextField(20);
        lblThongBao = new JLabel(" ");

        setLayout(new GridLayout(3, 1, 5, 5));

        JPanel pnlNhap = new JPanel(new FlowLayout(FlowLayout.LEFT));
        pnlNhap.add(lblEmail);
        pnlNhap.add(txtEmail);

        add(pnlNhap);
        add(lblThongBao);

        txtEmail.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                kiemTraEmail();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                kiemTraEmail();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                kiemTraEmail();
            }
        });
    }

    private void kiemTraEmail() {
        String email = txtEmail.getText().trim();

        // Regex email đơn giản (đủ cho LAB)
        String regexEmail = "^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$";

        if (email.isEmpty()) {
            lblThongBao.setText("Email không được để trống");
            lblThongBao.setForeground(Color.RED);
        } else if (!email.matches(regexEmail)) {
            lblThongBao.setText("Email không đúng định dạng");
            lblThongBao.setForeground(Color.RED);
        } else {
            lblThongBao.setText("Email hợp lệ");
            lblThongBao.setForeground(Color.GREEN);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Bai6().setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Bai6().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
